-- Napojenie na intervals.icu (Modules/Intervals) – sync recovery z hodiniek.
-- Riadok = user má sync zapnutý. Vypnutie: enabled = false.
--
-- RLS zapnuté BEZ policies: tabuľka drží API kľúč, takže user (anon /
-- authenticated) k nej nemá žiadny prístup. Číta a zapisuje len BE cez
-- service role. FE sa dozvie len bool cez /integrations/intervals/status.

create table if not exists public.intervals_accounts (
  id               bigint generated by default as identity primary key,
  user_id          bigint not null unique references public.users(id) on delete cascade,
  athlete_id       text   not null,           -- napr. "i123456" (intervals.icu → Settings)
  api_key          text   not null,           -- intervals.icu → Settings → Developer
  enabled          boolean not null default true,
  last_synced_at   timestamptz,
  last_error       text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

alter table public.intervals_accounts enable row level security;
revoke all on public.intervals_accounts from anon, authenticated;

-- Pridanie usera (doplň athlete_id a api_key):
-- insert into public.intervals_accounts (user_id, athlete_id, api_key)
-- values (46, 'i123456', 'API_KEY')
-- on conflict (user_id) do update
--   set athlete_id = excluded.athlete_id,
--       api_key    = excluded.api_key,
--       enabled    = true,
--       updated_at = now();
