-- Živý tréner: vlákna (správy) k tréningom medzi trénerom a zverencom.
-- Predpoklad: sql/trainer_links.sql.
--
-- Vlákno = jeden tréning: naplánovaná session (daily_plan_id) ALEBO aktivita
-- mimo plánu (activity_id). Keď sa aktivita spáruje s plánom, vlákno ostáva
-- na pláne.
--
-- daily_plan_id / activity_id zámerne BEZ FK: tréning sa dá zmazať alebo
-- presunúť, ale konverzácia o ňom má ostať.
--
-- link_id = spolupráca, v ktorej správa vznikla. Nový tréner tak nevidí
-- správy atléta s predchádzajúcim trénerom (atlét vidí všetky svoje).
--
-- RLS zapnuté BEZ policies: číta a zapisuje len BE cez service role
-- (Services/session_messages.py), ktorý overí, či volajúci je atlét alebo
-- jeho aktívny tréner.

create table if not exists public.session_messages (
  id               bigint generated by default as identity primary key,
  athlete_user_id  bigint not null references public.users(id) on delete cascade,
  link_id          bigint references public.trainer_links(id) on delete set null,
  daily_plan_id    bigint,
  activity_id      bigint,
  author_user_id   bigint not null references public.users(id) on delete cascade,
  body             text   not null check (char_length(body) between 1 and 2000),
  created_at       timestamptz not null default now(),
  read_at          timestamptz,              -- kedy si správu prečítal príjemca
  constraint session_messages_one_target
    check ((daily_plan_id is not null) <> (activity_id is not null))
);

create index if not exists session_messages_plan_idx
  on public.session_messages (athlete_user_id, daily_plan_id, created_at);

create index if not exists session_messages_activity_idx
  on public.session_messages (athlete_user_id, activity_id, created_at);

create index if not exists session_messages_unread_idx
  on public.session_messages (athlete_user_id, author_user_id)
  where read_at is null;

alter table public.session_messages enable row level security;
revoke all on public.session_messages from anon, authenticated;
