-- Živý tréner (fáza 1): párovanie tréner ↔ atlét cez 6-miestny kód.
--
-- users.share_code = kód, ktorý atlét pošle trénerovi. Zámerne nie users.id:
-- id idú po sebe, dajú sa uhádnuť a prezrádzajú počet userov. Kód si user
-- vie vygenerovať nanovo (stará žiadosť s ním ostane platná).
--
-- trainer_links = vzťah, nie rola. Ten istý user môže byť tréner aj atlét.
--   pending  -> tréner zadal kód, čaká sa na potvrdenie atléta
--   active   -> atlét potvrdil (najviac jeden aktívny tréner na atléta)
--   rejected -> atlét odmietol
--   canceled -> tréner stiahol žiadosť
--   ended    -> spolupráca ukončená (ktorákoľvek strana, ended_by)
-- Riadky sa nemažú – história súhlasov (GDPR: kto, kedy, čo).
--
-- RLS zapnuté BEZ policies: čítanie a zápis len BE cez service role
-- (vzťah sa týka dvoch userov, RLS jedného by druhého nevidel).
-- Vlastníctvo overuje route cez Modules/Supabase/ownership.is_owner.

alter table public.users
  add column if not exists share_code text;

create unique index if not exists users_share_code_key
  on public.users (share_code)
  where share_code is not null;

create table if not exists public.trainer_links (
  id               bigint generated by default as identity primary key,
  trainer_user_id  bigint not null references public.users(id) on delete cascade,
  athlete_user_id  bigint not null references public.users(id) on delete cascade,
  status           text   not null default 'pending'
                   check (status in ('pending', 'active', 'rejected', 'canceled', 'ended')),
  request_code     text,                       -- kód, ktorým tréner žiadal (trénerovi sa ukazuje namiesto mena, kým atlét nepotvrdí)
  created_at       timestamptz not null default now(),
  responded_at     timestamptz,
  ended_at         timestamptz,
  ended_by         bigint references public.users(id) on delete set null,
  constraint trainer_links_not_self check (trainer_user_id <> athlete_user_id)
);

-- Atlét má naraz najviac jedného aktívneho trénera.
create unique index if not exists trainer_links_one_active_per_athlete
  on public.trainer_links (athlete_user_id)
  where status = 'active';

-- Jedna čakajúca žiadosť na dvojicu.
create unique index if not exists trainer_links_one_pending_per_pair
  on public.trainer_links (trainer_user_id, athlete_user_id)
  where status = 'pending';

create index if not exists trainer_links_trainer_status_idx
  on public.trainer_links (trainer_user_id, status);

create index if not exists trainer_links_athlete_status_idx
  on public.trainer_links (athlete_user_id, status);

alter table public.trainer_links enable row level security;
revoke all on public.trainer_links from anon, authenticated;
