# Configs/strength_catalog.py
"""
Obohatený katalóg silových cvikov.

Oproti pôvodnej verzii (id/name_en/target/equipment) pribudli polia, ktoré
umožňujú DETERMINISTICKÝ výber cvikov v kóde namiesto toho, aby si AI
vyberala naslepo z plochého zoznamu:

- pattern            pohybový vzor (squat/hinge/pull_v/carry/...) - zabezpečí
                     vyváženosť tréningu (nie 3x tlak a 0x ťah)
- tier               primary/secondary/accessory/prehab - riadi, koľko sérií
                     a akú pauzu cvik dostane (viď Services/strength/schemes.py)
- load_type          čím sa zaťažuje - primárny signál "loaded vs bodyweight"
- unilateral         jednostranný pohyb (dôležité pre bežcov a Hyrox)
- skill_demand       technická náročnosť - začiatočník nedostane turkish get-up
- fatigue_cost       koľko to zoberie do ďalších dní (plánovanie okolo behov)
- eccentric_load     vysoké = svalové poškodenie = NEDÁVAŤ pred kvalitný beh
- rep_suitability    na aké ciele sa cvik hodí (dead hang nie je na 5x3 na silu)
- sport_tags         šport-špecifická relevancia
- contraindications  pri ktorých zraneniach cvik vynechať

`target` zostáva kvôli spätnej kompatibilite (coach_strength_mapper menu
+ strength history slot).
"""

# pattern: squat | hinge | lunge | push_h | push_v | pull_h | pull_v |
#          carry | rotation | anti_rotation | anti_extension | jump | calf | grip
# tier: primary | secondary | accessory | prehab
# load_type: barbell | dumbbell | kettlebell | machine | cable | band | bodyweight | implement
# skill_demand / fatigue_cost / eccentric_load: low | med | high
# rep_suitability: strength | hypertrophy | endurance | power
# sport_tags: general | running | hyrox | ocr | swimming | triathlon

STRENGTH_EXERCISE_CATALOG = [
    # ================= CORE =================
    {
        "id": "plank", "name_en": "Plank", "target": "core",
        "pattern": "anti_extension", "tier": "prehab", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running", "ocr"],
        "contraindications": [],
    },
    {
        "id": "side_plank", "name_en": "Side Plank", "target": "core",
        "pattern": "anti_rotation", "tier": "prehab", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "abwheel_rollout", "name_en": "Ab Wheel Rollout", "target": "core",
        "pattern": "anti_extension", "tier": "accessory", "equipment": ["abwheel"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "high",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general", "ocr"],
        "contraindications": ["lower_back", "shoulder"],
    },
    {
        "id": "hanging_knee_raise", "name_en": "Hanging Knee Raise", "target": "core",
        "pattern": "anti_extension", "tier": "accessory", "equipment": ["pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "cable_chop", "name_en": "Cable Woodchop", "target": "core",
        "pattern": "rotation", "tier": "accessory", "equipment": ["cable"],
        "load_type": "cable", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "endurance", "power"],
        "sport_tags": ["general", "running", "swimming", "ocr"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "bird_dog", "name_en": "Bird-Dog", "target": "core",
        "pattern": "anti_rotation", "tier": "prehab", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running"],
        "contraindications": [],
    },
    {
        "id": "dead_bug", "name_en": "Dead Bug", "target": "core",
        "pattern": "anti_extension", "tier": "prehab", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running"],
        "contraindications": [],
    },
    {
        "id": "russian_twist", "name_en": "Russian Twist", "target": "core",
        "pattern": "rotation", "tier": "accessory",
        "equipment": ["none", "dumbbell", "kettlebell"],
        "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance", "hypertrophy"], "sport_tags": ["general", "ocr"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "mountain_climber", "name_en": "Mountain Climber", "target": "core",
        "pattern": "anti_extension", "tier": "accessory", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": [],
    },
    {
        "id": "hollow_body_hold", "name_en": "Hollow Body Hold", "target": "core",
        "pattern": "anti_extension", "tier": "accessory", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "medicine_ball_rotational_throw", "name_en": "Rotational Med Ball Throw",
        "target": "core", "pattern": "rotation", "tier": "accessory",
        "equipment": ["medicine_ball"], "load_type": "implement", "unilateral": True,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["power"], "sport_tags": ["general", "ocr", "swimming"],
        "contraindications": ["lower_back", "shoulder"],
    },

    # ================= LOWER BODY (QUADS) =================
    {
        "id": "bodyweight_squat", "name_en": "Bodyweight Squat", "target": "lower_quad",
        "pattern": "squat", "tier": "accessory", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running"],
        "contraindications": [],
    },
    {
        "id": "barbell_back_squat", "name_en": "Barbell Back Squat", "target": "lower_quad",
        "pattern": "squat", "tier": "primary", "equipment": ["barbell"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "running", "hyrox", "ocr"],
        "contraindications": ["knee", "lower_back"],
    },
    {
        "id": "front_squat_barbell", "name_en": "Barbell Front Squat", "target": "lower_quad",
        "pattern": "squat", "tier": "primary", "equipment": ["barbell"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "hyrox"],
        "contraindications": ["knee", "lower_back", "shoulder"],
    },
    {
        "id": "leg_press_machine", "name_en": "Leg Press", "target": "lower_quad",
        "pattern": "squat", "tier": "secondary", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["strength", "hypertrophy", "endurance"],
        "sport_tags": ["general", "running"],
        "contraindications": ["knee"],
    },
    {
        "id": "split_squat", "name_en": "Split Squat", "target": "lower_quad",
        "pattern": "lunge", "tier": "secondary", "equipment": ["none", "dumbbell"],
        "load_type": "dumbbell", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "running", "hyrox", "triathlon"],
        "contraindications": ["knee"],
    },
    {
        "id": "goblet_squat", "name_en": "Goblet Squat", "target": "lower_quad",
        "pattern": "squat", "tier": "secondary", "equipment": ["dumbbell", "kettlebell"],
        "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["knee"],
    },
    {
        "id": "box_stepup", "name_en": "Box Step-up", "target": "lower_quad",
        "pattern": "lunge", "tier": "secondary", "equipment": ["none", "dumbbell", "box"],
        "load_type": "dumbbell", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "running", "hyrox", "ocr"],
        "contraindications": ["knee"],
    },
    {
        "id": "bulgarian_split_squat", "name_en": "Bulgarian Split Squat",
        "target": "lower_quad", "pattern": "lunge", "tier": "secondary",
        "equipment": ["none", "dumbbell", "bench"], "load_type": "dumbbell",
        "unilateral": True,
        "skill_demand": "med", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["hypertrophy", "strength"],
        "sport_tags": ["general", "running", "hyrox"],
        "contraindications": ["knee"],
    },
    {
        "id": "walking_lunge", "name_en": "Walking Lunge", "target": "lower_quad",
        "pattern": "lunge", "tier": "secondary", "equipment": ["none", "dumbbell"],
        "load_type": "dumbbell", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["knee"],
    },
    {
        "id": "hack_squat_machine", "name_en": "Hack Squat", "target": "lower_quad",
        "pattern": "squat", "tier": "secondary", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "high",
        "rep_suitability": ["hypertrophy", "strength"], "sport_tags": ["general"],
        "contraindications": ["knee"],
    },
    {
        "id": "leg_extension_machine", "name_en": "Leg Extension", "target": "lower_quad",
        "pattern": "squat", "tier": "accessory", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general"],
        "contraindications": ["knee"],
    },

    # ================= LOWER BODY (POSTERIOR) =================
    {
        "id": "glute_bridge_bodyweight", "name_en": "Glute Bridge",
        "target": "lower_posterior", "pattern": "hinge", "tier": "prehab",
        "equipment": ["none"], "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running"],
        "contraindications": [],
    },
    {
        "id": "romanian_deadlift_barbell", "name_en": "Barbell Romanian Deadlift",
        "target": "lower_posterior", "pattern": "hinge", "tier": "primary",
        "equipment": ["barbell"], "load_type": "barbell", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "running", "hyrox"],
        "contraindications": ["lower_back", "hamstring"],
    },
    {
        "id": "romanian_deadlift_dumbbell", "name_en": "Dumbbell RDL",
        "target": "lower_posterior", "pattern": "hinge", "tier": "secondary",
        "equipment": ["dumbbell"], "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "high",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "running", "hyrox"],
        "contraindications": ["lower_back", "hamstring"],
    },
    {
        "id": "single_leg_deadlift_band", "name_en": "Single Leg Deadlift",
        "target": "lower_posterior", "pattern": "hinge", "tier": "accessory",
        "equipment": ["none", "resistance_bands", "dumbbell"], "load_type": "dumbbell",
        "unilateral": True,
        "skill_demand": "med", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["endurance", "hypertrophy"],
        "sport_tags": ["general", "running", "triathlon"],
        "contraindications": ["hamstring"],
    },
    {
        "id": "hamstring_curl_machine", "name_en": "Hamstring Curl",
        "target": "lower_posterior", "pattern": "hinge", "tier": "accessory",
        "equipment": ["machine"], "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general", "running"],
        "contraindications": ["hamstring"],
    },
    {
        "id": "hip_thrust_barbell", "name_en": "Barbell Hip Thrust",
        "target": "lower_posterior", "pattern": "hinge", "tier": "secondary",
        "equipment": ["barbell", "bench"], "load_type": "barbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "running", "hyrox"],
        "contraindications": [],
    },
    {
        "id": "kettlebell_swing", "name_en": "Kettlebell Swing",
        "target": "lower_posterior", "pattern": "hinge", "tier": "secondary",
        "equipment": ["kettlebell", "dumbbell"], "load_type": "kettlebell",
        "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["power", "endurance"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "conventional_deadlift", "name_en": "Conventional Deadlift",
        "target": "lower_posterior", "pattern": "hinge", "tier": "primary",
        "equipment": ["barbell"], "load_type": "barbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["strength"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["lower_back", "hamstring"],
    },
    {
        "id": "good_morning_barbell", "name_en": "Barbell Good Morning",
        "target": "lower_posterior", "pattern": "hinge", "tier": "accessory",
        "equipment": ["barbell"], "load_type": "barbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "med", "eccentric_load": "high",
        "rep_suitability": ["hypertrophy"], "sport_tags": ["general"],
        "contraindications": ["lower_back", "hamstring"],
    },
    {
        "id": "back_extension", "name_en": "Back Extension",
        "target": "lower_posterior", "pattern": "hinge", "tier": "accessory",
        "equipment": ["machine", "none"], "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["endurance", "hypertrophy"], "sport_tags": ["general", "running"],
        "contraindications": ["lower_back"],
    },

    # ================= CALVES & ANKLES =================
    {
        "id": "standing_calf_raise", "name_en": "Standing Calf Raise",
        "target": "lower_calves", "pattern": "calf", "tier": "accessory",
        "equipment": ["none", "dumbbell", "machine"], "load_type": "dumbbell",
        "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "running", "triathlon"],
        "contraindications": ["achilles"],
    },
    {
        "id": "seated_calf_raise", "name_en": "Seated Calf Raise",
        "target": "lower_calves", "pattern": "calf", "tier": "accessory",
        "equipment": ["machine", "dumbbell"], "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general", "running"],
        "contraindications": ["achilles"],
    },
    {
        "id": "single_leg_calf_raise", "name_en": "Single Leg Calf Raise",
        "target": "lower_calves", "pattern": "calf", "tier": "accessory",
        "equipment": ["none", "dumbbell"], "load_type": "bodyweight", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["endurance", "hypertrophy"],
        "sport_tags": ["general", "running", "triathlon", "ocr"],
        "contraindications": ["achilles"],
    },
    {
        "id": "jump_rope", "name_en": "Jump Rope (Pogo Jumps)",
        "target": "lower_calves", "pattern": "jump", "tier": "accessory",
        "equipment": ["none"], "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["power", "endurance"],
        "sport_tags": ["general", "running", "ocr"],
        "contraindications": ["achilles", "shin", "knee"],
    },
    {
        "id": "tibialis_raise", "name_en": "Tibialis Raise",
        "target": "lower_calves", "pattern": "calf", "tier": "prehab",
        "equipment": ["none", "resistance_bands"], "load_type": "bodyweight",
        "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "running"],
        "contraindications": [],
    },

    # ================= UPPER PULL =================
    {
        "id": "bodyweight_row", "name_en": "Inverted Row", "target": "upper_pull",
        "pattern": "pull_h", "tier": "secondary", "equipment": ["barbell", "trx"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance", "hypertrophy"],
        "sport_tags": ["general", "ocr", "swimming"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "trx_row", "name_en": "TRX Row", "target": "upper_pull",
        "pattern": "pull_h", "tier": "secondary", "equipment": ["trx"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance", "hypertrophy"],
        "sport_tags": ["general", "ocr", "swimming"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "lat_pulldown_machine", "name_en": "Lat Pulldown", "target": "upper_pull",
        "pattern": "pull_v", "tier": "secondary", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "swimming", "hyrox", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "pullup_assisted", "name_en": "Assisted Pull-up", "target": "upper_pull",
        "pattern": "pull_v", "tier": "secondary", "equipment": ["pullup_bar", "machine"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "pullup_strict", "name_en": "Strict Pull-up", "target": "upper_pull",
        "pattern": "pull_v", "tier": "primary", "equipment": ["pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "ocr", "swimming"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "dumbbell_row", "name_en": "Single Arm Dumbbell Row", "target": "upper_pull",
        "pattern": "pull_h", "tier": "secondary", "equipment": ["dumbbell", "bench"],
        "load_type": "dumbbell", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "strength"],
        "sport_tags": ["general", "swimming", "hyrox"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "barbell_row", "name_en": "Barbell Bent-Over Row", "target": "upper_pull",
        "pattern": "pull_h", "tier": "primary", "equipment": ["barbell"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "seated_cable_row", "name_en": "Seated Cable Row", "target": "upper_pull",
        "pattern": "pull_h", "tier": "secondary", "equipment": ["cable"],
        "load_type": "cable", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "endurance"],
        "sport_tags": ["general", "swimming", "hyrox"],
        "contraindications": [],
    },
    {
        "id": "face_pull", "name_en": "Face Pull", "target": "upper_pull",
        "pattern": "pull_h", "tier": "prehab", "equipment": ["cable", "resistance_bands"],
        "load_type": "cable", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance", "hypertrophy"],
        "sport_tags": ["general", "swimming"],
        "contraindications": [],
    },
    {
        "id": "chin_up", "name_en": "Chin-up", "target": "upper_pull",
        "pattern": "pull_v", "tier": "primary", "equipment": ["pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "band_pull_apart", "name_en": "Band Pull-Apart", "target": "upper_pull",
        "pattern": "pull_h", "tier": "prehab", "equipment": ["resistance_bands", "none"],
        "load_type": "band", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "swimming"],
        "contraindications": [],
    },
    {
        "id": "cable_external_rotation", "name_en": "Cable External Rotation (Rotator Cuff)",
        "target": "upper_pull", "pattern": "pull_h", "tier": "prehab",
        "equipment": ["cable", "resistance_bands"], "load_type": "cable", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "swimming", "triathlon"],
        "contraindications": [],
    },

    # ================= UPPER PUSH =================
    {
        "id": "pushup", "name_en": "Push-up", "target": "upper_push",
        "pattern": "push_h", "tier": "accessory", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance", "hypertrophy"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "bench_press_barbell", "name_en": "Barbell Bench Press", "target": "upper_push",
        "pattern": "push_h", "tier": "primary", "equipment": ["barbell", "bench"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["strength", "hypertrophy"], "sport_tags": ["general"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "incline_db_press", "name_en": "Incline Dumbbell Press", "target": "upper_push",
        "pattern": "push_h", "tier": "secondary", "equipment": ["dumbbell", "bench"],
        "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy"], "sport_tags": ["general"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "shoulder_press_dumbbell", "name_en": "Dumbbell Shoulder Press",
        "target": "upper_push", "pattern": "push_v", "tier": "secondary",
        "equipment": ["dumbbell"], "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "strength"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "dip_assisted", "name_en": "Assisted Dips", "target": "upper_push",
        "pattern": "push_v", "tier": "secondary", "equipment": ["machine", "pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "dip_strict", "name_en": "Strict Dips", "target": "upper_push",
        "pattern": "push_v", "tier": "primary", "equipment": ["pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "high",
        "rep_suitability": ["strength", "hypertrophy"], "sport_tags": ["general", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "overhead_press_barbell", "name_en": "Overhead Press", "target": "upper_push",
        "pattern": "push_v", "tier": "primary", "equipment": ["barbell"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["strength", "hypertrophy"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": ["shoulder", "lower_back"],
    },
    {
        "id": "push_press", "name_en": "Push Press", "target": "upper_push",
        "pattern": "push_v", "tier": "primary", "equipment": ["barbell", "dumbbell"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["power", "strength"], "sport_tags": ["general", "hyrox"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "pec_deck_fly", "name_en": "Pec Deck Fly", "target": "upper_push",
        "pattern": "push_h", "tier": "accessory", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "med",
        "rep_suitability": ["hypertrophy"], "sport_tags": ["general"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "triceps_pushdown", "name_en": "Cable Triceps Pushdown", "target": "upper_push",
        "pattern": "push_v", "tier": "accessory", "equipment": ["cable"],
        "load_type": "cable", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["hypertrophy", "endurance"], "sport_tags": ["general"],
        "contraindications": [],
    },
    {
        "id": "scapular_pushup", "name_en": "Scapular Push-up (Shoulder Health)",
        "target": "upper_push", "pattern": "push_h", "tier": "prehab",
        "equipment": ["none"], "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["general", "swimming"],
        "contraindications": [],
    },

    # ================= FUNCTIONAL / HYROX / OCR =================
    {
        "id": "farmers_carry", "name_en": "Farmer's Carry", "target": "functional",
        "pattern": "carry", "tier": "secondary", "equipment": ["dumbbell", "kettlebell"],
        "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["endurance", "strength"],
        "sport_tags": ["general", "hyrox", "ocr"],
        "contraindications": [],
    },
    {
        "id": "sandbag_carry", "name_en": "Sandbag Carry", "target": "functional",
        "pattern": "carry", "tier": "secondary", "equipment": ["sandbag"],
        "load_type": "implement", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["ocr", "hyrox"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "bucket_carry", "name_en": "Bucket Carry", "target": "functional",
        "pattern": "carry", "tier": "secondary", "equipment": ["sandbag", "implement"],
        "load_type": "implement", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["ocr"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "sled_push", "name_en": "Sled Push", "target": "functional",
        "pattern": "squat", "tier": "secondary", "equipment": ["machine"],
        "load_type": "implement", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "low",
        "rep_suitability": ["strength", "endurance", "power"],
        "sport_tags": ["hyrox", "ocr"],
        "contraindications": [],
    },
    {
        "id": "sled_pull", "name_en": "Sled Pull", "target": "functional",
        "pattern": "pull_h", "tier": "secondary", "equipment": ["machine"],
        "load_type": "implement", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "low",
        "rep_suitability": ["strength", "endurance"], "sport_tags": ["hyrox"],
        "contraindications": [],
    },
    {
        "id": "ski_erg", "name_en": "Ski Erg", "target": "functional",
        "pattern": "pull_v", "tier": "secondary", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["hyrox"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "rowing_erg", "name_en": "Rowing Machine (Erg)", "target": "functional",
        "pattern": "pull_h", "tier": "secondary", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["hyrox", "triathlon"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "assault_bike", "name_en": "Assault Bike / Echo Bike", "target": "functional",
        "pattern": "jump", "tier": "accessory", "equipment": ["machine"],
        "load_type": "machine", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["endurance", "power"], "sport_tags": ["hyrox", "general"],
        "contraindications": [],
    },
    {
        "id": "wall_ball", "name_en": "Wall Ball Shot", "target": "functional",
        "pattern": "squat", "tier": "secondary", "equipment": ["medicine_ball"],
        "load_type": "implement", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "high", "eccentric_load": "med",
        "rep_suitability": ["endurance", "power"], "sport_tags": ["hyrox"],
        "contraindications": ["shoulder", "knee"],
    },
    {
        "id": "thruster", "name_en": "Thruster (Squat to Press)", "target": "functional",
        "pattern": "push_v", "tier": "primary", "equipment": ["barbell", "dumbbell", "kettlebell"],
        "load_type": "barbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "high", "eccentric_load": "med",
        "rep_suitability": ["power", "endurance"], "sport_tags": ["hyrox"],
        "contraindications": ["shoulder", "knee"],
    },
    {
        "id": "sandbag_lunge", "name_en": "Sandbag Walking Lunge", "target": "functional",
        "pattern": "lunge", "tier": "secondary", "equipment": ["sandbag", "dumbbell"],
        "load_type": "implement", "unilateral": True,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "high",
        "rep_suitability": ["endurance"], "sport_tags": ["hyrox", "ocr"],
        "contraindications": ["knee", "lower_back"],
    },
    {
        "id": "box_jump", "name_en": "Box Jump", "target": "functional",
        "pattern": "jump", "tier": "secondary", "equipment": ["box", "none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["power"], "sport_tags": ["general", "hyrox", "ocr", "running"],
        "contraindications": ["knee", "achilles"],
    },
    {
        "id": "broad_jump", "name_en": "Standing Broad Jump", "target": "functional",
        "pattern": "jump", "tier": "secondary", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "med", "fatigue_cost": "med", "eccentric_load": "high",
        "rep_suitability": ["power"], "sport_tags": ["hyrox", "ocr"],
        "contraindications": ["knee", "achilles"],
    },
    {
        "id": "burpee", "name_en": "Burpee", "target": "functional",
        "pattern": "jump", "tier": "accessory", "equipment": ["none"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "high", "eccentric_load": "med",
        "rep_suitability": ["endurance"], "sport_tags": ["hyrox", "ocr"],
        "contraindications": ["knee", "shoulder"],
    },
    {
        "id": "devils_press", "name_en": "Devil's Press", "target": "functional",
        "pattern": "push_v", "tier": "secondary", "equipment": ["dumbbell"],
        "load_type": "dumbbell", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "high", "eccentric_load": "med",
        "rep_suitability": ["endurance", "power"], "sport_tags": ["hyrox", "ocr"],
        "contraindications": ["shoulder", "lower_back"],
    },
    {
        "id": "turkish_getup", "name_en": "Turkish Get-Up", "target": "functional",
        "pattern": "anti_rotation", "tier": "accessory",
        "equipment": ["kettlebell", "dumbbell"], "load_type": "kettlebell", "unilateral": True,
        "skill_demand": "high", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["strength"], "sport_tags": ["general", "ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "kettlebell_clean_and_press", "name_en": "Kettlebell Clean & Press",
        "target": "functional", "pattern": "push_v", "tier": "secondary",
        "equipment": ["kettlebell"], "load_type": "kettlebell", "unilateral": True,
        "skill_demand": "high", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["power", "strength"], "sport_tags": ["general", "ocr", "hyrox"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "medicine_ball_slam", "name_en": "Medicine Ball Slam", "target": "functional",
        "pattern": "rotation", "tier": "accessory", "equipment": ["medicine_ball"],
        "load_type": "implement", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "med", "eccentric_load": "low",
        "rep_suitability": ["power", "endurance"], "sport_tags": ["general", "ocr"],
        "contraindications": ["lower_back"],
    },
    {
        "id": "rope_climb", "name_en": "Rope Climb", "target": "functional",
        "pattern": "pull_v", "tier": "secondary", "equipment": ["implement"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "high", "eccentric_load": "med",
        "rep_suitability": ["strength"], "sport_tags": ["ocr"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "dead_hang", "name_en": "Dead Hang (Grip Endurance)", "target": "functional",
        "pattern": "grip", "tier": "accessory", "equipment": ["pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "low", "fatigue_cost": "low", "eccentric_load": "low",
        "rep_suitability": ["endurance"], "sport_tags": ["ocr", "hyrox"],
        "contraindications": ["shoulder"],
    },
    {
        "id": "monkey_bar_traverse", "name_en": "Monkey Bar Traverse", "target": "functional",
        "pattern": "grip", "tier": "secondary", "equipment": ["pullup_bar"],
        "load_type": "bodyweight", "unilateral": False,
        "skill_demand": "high", "fatigue_cost": "med", "eccentric_load": "med",
        "rep_suitability": ["endurance", "strength"], "sport_tags": ["ocr"],
        "contraindications": ["shoulder"],
    },
]


# ============================================================
# POMOCNÉ INDEXY (pripravené pre selector.py)
# ============================================================

CATALOG_BY_ID = {ex["id"]: ex for ex in STRENGTH_EXERCISE_CATALOG}

ALL_PATTERNS = sorted({ex["pattern"] for ex in STRENGTH_EXERCISE_CATALOG})
ALL_TARGETS = sorted({ex["target"] for ex in STRENGTH_EXERCISE_CATALOG})
ALL_SPORT_TAGS = sorted({tag for ex in STRENGTH_EXERCISE_CATALOG for tag in ex["sport_tags"]})


def get_exercise(exercise_id: str):
    """Vráti cvik z katalógu podľa id, alebo None."""
    return CATALOG_BY_ID.get(exercise_id)


def is_loaded(exercise: dict) -> bool:
    """True ak cvik vie byť zaťažený externou váhou (nie je bodyweight-only)."""
    return exercise.get("load_type") != "bodyweight" or exercise.get("equipment") != ["none"]