import os
from dotenv import load_dotenv

load_dotenv()

TABLE_ACTIVITIES_SUMMARY = os.getenv("TABLE_ACTIVITIES_SUMMARY")
TABLE_ACTIVITY_DETAILS = os.getenv("TABLE_ACTIVITY_DETAILS")
TABLE_ACTIVITIES_SPLITS = os.getenv("TABLE_ACTIVITIES_SPLITS")
TABLE_ACTIVITIES_LAPS = os.getenv("TABLE_ACTIVITIES_LAPS")
TABLE_ACTIVITIES_RAW = os.getenv("TABLE_ACTIVITIES_RAW")
TABLE_USERS = os.getenv("TABLE_USERS")
TABLE_USERS_PROFILE = os.getenv("TABLE_USERS_PROFILE")
TABLE_USERS_ZONES = os.getenv("TABLE_USERS_ZONES")
TABLE_USERS_THRESHOLDS = os.getenv("TABLE_USERS_THRESHOLDS")
TABLE_USERS_BESTS = os.getenv("TABLE_USERS_BESTS")
TABLE_USERS_RECOVERY = os.getenv("TABLE_USERS_RECOVERY")

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE = os.getenv("SUPABASE_SERVICE_ROLE")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")